api_hash: your_api_hash
api_id: your_api_id
chat:
  - chat_id: telegram_chat_id
    last_read_message_id: 0
    download_filter: message_date >= 2022-12-01 00:00:00 and message_date <= 2023-01-17 00:00:00
  - chat_id: telegram_chat_id_2
    last_read_message_id: 0
# note we remove ids_to_retry to data.yaml
ids_to_retry: []
media_types:
  - audio
  - document
  - photo
  - video
  - voice
  - animation #gif
file_formats:
  audio:
    - all
  document:
    - pdf
    - epub
  video:
    - mp4
save_path: D:\telegram_media_downloader
file_path_prefix:
  - chat_title
  - media_datetime
upload_drive:
  # required
  enable_upload_file: true
  # required
  remote_dir: drive:/telegram
  # required
  upload_adapter: rclone
  # option,when config upload_adapter rclone then this config are required
  rclone_path: D:\rclone\rclone.exe
  # option
  before_upload_file_zip: True
  # option
  after_upload_file_delete: True
hide_file_name: true
file_name_prefix:
  - message_id
  - file_name
file_name_prefix_split: " - "
max_download_task: 5
web_host: 127.0.0.1
web_port: 5000
language: EN
web_login_secret: 123
allowed_user_ids:
  - "me"
date_format: "%Y_%m"
